// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBnmCHqyJIm3uRNBvdMGtzsinNpAX9nqU',
    appId: '1:100717283384:web:9cfedfdfa826144241fecd',
    messagingSenderId: '100717283384',
    projectId: 'look8me-e87bb',
    authDomain: 'look8me-e87bb.firebaseapp.com',
    storageBucket: 'look8me-e87bb.appspot.com',
    measurementId: 'G-9Y5D8VVH4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM8JaGrl3H_57DENoewKNGX2ZHjdwNCYs',
    appId: '1:100717283384:android:0800f4b005bb0a4141fecd',
    messagingSenderId: '100717283384',
    projectId: 'look8me-e87bb',
    storageBucket: 'look8me-e87bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWkhqr8r2AujxzuvytuFNMqa0go1zlcus',
    appId: '1:100717283384:ios:2bc9616a484274a841fecd',
    messagingSenderId: '100717283384',
    projectId: 'look8me-e87bb',
    storageBucket: 'look8me-e87bb.appspot.com',
    iosBundleId: 'com.example.look8me',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWkhqr8r2AujxzuvytuFNMqa0go1zlcus',
    appId: '1:100717283384:ios:1c348024d751939f41fecd',
    messagingSenderId: '100717283384',
    projectId: 'look8me-e87bb',
    storageBucket: 'look8me-e87bb.appspot.com',
    iosBundleId: 'com.example.look8me.RunnerTests',
  );
}
